backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
site_url: https://10gadget.com
logo_url: https://10gadget.com/assets/images/logo/logo.svg
collections:  
 - name: "blog"    
   label: "Blog"    
   folder: "_posts/"    
   create: true # Allow users to create new documents  
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   editor:      
    preview: false    
   fields: # The fields for each document, usually in front matter         
     - { label: "Layout", 
         name: "layout", 
         widget: "hidden", 
         default: "post" }      
     - { label: "Title", name: "title", widget: "string" }      
     - { label: "date", name: "date", widget: "datetime" }      
     - { label: "authors",          
         name: "authors",          
         widget: "relation",          
         collection: "authors",          
         displayFields: [display_name],          
         searchFields: [display_name],          
         valueField: "name", }
     - { label: "categories",          
         name: "categories",          
         widget: "relation",          
         collection: "categories",          
         displayFields: [display_name],          
         searchFields: [display_name],          
         valueField: "name", }
     - { label: "description", name: "description", widget: "string" }        
     - { label: "Body", name: "body", widget: "html" }